---
- name: Check user on OpenStack environment
  hosts: local
  connection: local
  gather_facts: false
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ playbook_dir }}/clouds.yml"
    OS_IDENTITY_API_VERSION: 3

  tasks:
    - name: Authenticate to specified OpenStack provider
      os_auth:
        cloud: mycloud

    - os_user_role:
        auth:
          auth_url: http://172.22.26.201:5000/v3
          username: admin
          password: 50937613b1734615
          project_name: admin
          project_domain_name: Default
          user_domain_name: Default
        user: demouser
        role: admin
        project: demo
      register: user_state

    - name: If user role is changed to admin
      os_user_role:
        auth:
          auth_url: http://172.22.26.201:5000/v3
          username: admin
          password: 50937613b1734615
          project_name: admin
          project_domain_name: Default
          user_domain_name: Default
        user: demouser
        state: absent
        role: admin
        project: demo
      when: user_state|changed

    - name: Send mail if user has permission
      mail:
        host: smtp.mailtrap.io
        port: 2525
        username: de4d09c4618605
        password: 5b4c2999adb544
        to: User <user@gmail.com>
        subject: Request-report
        body: 'demouser has no permission to launch instance'
      when: user_state|changed

    - name : Debug
      debug:
        var: user_state

