---
- name: Check user permissions on OpenStack environment
  hosts: local
  connection: local
  gather_facts: false
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ playbook_dir }}/clouds.yml"
    OS_IDENTITY_API_VERSION: 3

  tasks:
    - name: Authenticate to specified OpenStack provider
      os_auth:
        cloud: mycloud

    - name: Grant admin role to user and grab changes
      block:
        - os_user_role:
            auth:
              auth_url: http://172.22.26.201:5000/v3
              username: admin
              password: 50937613b1734615
              project_name: admin
              project_domain_name: Default
              user_domain_name: Default
            user: demouser
            role: admin
            project: demo
          register: user_state
      rescue:
        - name: user don't exist
          set_fact:
            message: "User don't exist"

    - name: If user role is changed to admin
      os_user_role:
        auth:
          auth_url: http://172.22.26.201:5000/v3
          username: admin
          password: 50937613b1734615
          project_name: admin
          project_domain_name: Default
          user_domain_name: Default
        user: demouser
        state: absent
        role: admin
        project: demo
      when: user_state|changed

    - name: Set message if user is not admin
      set_fact:
        message: "demouser don't have privileges for OpenStack provider"
      when: user_state|changed

    - name: Set message if user is admin
      set_fact:
        message: "demouser have privileges for OpenStack provider"
      when: message is undefined

    - name: Send mail
      mail:
        host: smtp.mailtrap.io
        port: 2525
        username: de4d09c4618605
        password: 5b4c2999adb544
        to: User <user@gmail.com>
        subject: Request-report
        body: "{{ message }}"
      when: message is defined

    - name : Debug
      debug:
        var: user_state